{% set name = "vertica-python" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vertica-python-{{ version }}.tar.gz
  sha256: f042cf60ddd69eeb17c9f1586bae25da5b7282ca53d9afe0be30b943b4194d52

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - python-dateutil >=1.5
    - six >=1.10.0

test:
  imports:
    - vertica_python
    - vertica_python.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vertica/vertica-python
  summary: A native Python client for the Vertica database.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmlandwehr
